version: '3.8'

services:
  xaia_db:
    image: mysql:8.0
    container_name: xaia_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xaia
    command: --bind-address=0.0.0.0
    ports:
      - "3306:3306"
    volumes:
      - xaia_db_data:/var/lib/mysql

volumes:
  xaia_db_data: